spring:
  application:
    name: postgres-app
  config:
    import: optional:configserver:http://localhost:8090
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      client:
        url: http://localhost:8080

    logging:
      file:
        path: "E:\\Projects\\postgres-app"

    management:
      endpoints:
        web:
          exposure:
            include: '*'
      endpoint:
        health:
          show-details: always


